# Descriptions
title: Dustin Kocher
email: dtkocher@hotmail.com
description: >
  Dustin Kocher is a Father, Husband, Friend, and last but not least a
  Solutions Engineer. Enjoys creating great software and user experiences
  using several different technologies. Specializes in Ruby on Rails, J2EE,
  AngularJS, and Bootstrap for web applications and RubyMotion for both Iphone
  and Android applications.
keywords: >
  Freelancer, Ruby on Rails, Software Engineer

# urls
url: "http://dustinkocher.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Social names
twitter_username: DustinKocher
github_username:  dtkocher
linkedin_username:  dtkocher

# Build settings
paginate: 5
paginate_path: "blog/page:num"

highlighter: pygments
markdown: redcarpet

sass:
  syntax: scss
  style: compressed

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']
